- name: vars preference
  hosts: local
  connection: local
  vars:
    NAME: from play level
  # vars_files:
  # - course.yaml
  # vars_prompt:
  # - name: NAME
  #   prompt: What is your NAME?
  #   private: false
  tasks:
  - name: testing variables preference
    # vars:
    #   NAME: from task level
    ansible.builtin.debug:
      msg: "Name is: {{ NAME }}"

  # 1st preference is commad line
  # ansible-playbook -i inventory.ini -e ansible_user=ec2_user -e ansible_password=DevOps321 -e "NAME=From-command-line" 10-vars-preference.yaml
  # 2. from task level
  # 3. from files
  # 4. from prompt
