- name: data types
  hosts: local
  connections: local
  vars:
    Course: "DevOps with AWS" #string
    Duration: 120 #number
    is_live: true #boolean
    # list
    tools: #["linux","shell","ansible"]
    - "linux"
    - "shell"
    - "ansible"
  # dictionary or map
    concepts:
      cloud: aws
      cm: ansible
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Course name: {{ Course }}, Duration: {{ Duration }}, is_live: {{ is_live }}, tools: {{ tools }}, concepts: {{ concepts }}"

# list: []
# map: {}